version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "Welcome1"
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "Welcome1"
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  network1:
    ipam:
      driver: default